### ISSUE TITLE
wikitablescrape --url is failing 

### ISSUE THREAD

**Issue by gargashish11** [rocheio/wiki-table-scrape#6]
Following command is failing
wikitablescrape --url="https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools#Other_features" --output-folder=.

Perhaps due to presence of a forward slash in the name of one of the tables.Parsing all tables from 'https://en.wikipedia.org/wiki/Comparison_of_file_comparison_tools#Other_features' into '.'
Writing table 1 to ./general.csv
Writing table 2 to ./compare_features.csv
Writing table 3 to ./api_/_editor_features.csv
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory: './api_/_editor_features.csv'

I guess the forward slash is being read as diretory seperator character. 

Thanks a lot for the tool.

**Comment by rocheio** [comment]
@gargashish11 thank you for reporting the bug! I fixed it with https://github.com/rocheio/wiki-table-scrape/pull/7 by removing the slash as you suggested.

I also added a test for this which can be easily built out with more cases, so if you find any other weird header -> filename issues you can open an issue or PR to fix and I'll gladly take a look and we should be able to get them all covered.

I pushed an updated version (`1.0.3`) to the master branch and `pip`, so you should be able to upgrade now and get this page working.
